### ISSUE TITLE
Cannot take gradient of VJP function involving new-style RNG key

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#18442]
### Description
```python
from jax import custom_vjp, grad
from jax.random import key

@custom_vjp
def find_fixed_point(theta, state):
    return state

def _ffp_fwd(theta, state):
    return state, None

def _ffp_bwd(residuals, state_bar):
    assert False

find_fixed_point.defvjp(_ffp_fwd, _ffp_bwd)

def fixed_point_using_while_of_theta(theta) -> float:
    state = (8.0, key(123))
    x, _ = find_fixed_point(theta, state)
    return x

grad(fixed_point_using_while_of_theta)(3.0)
```
gives
```
ValueError: Cannot convert_element_type to dtype=key<fry>
```
@froystig 

### What jax/jaxlib version are you using?

0.4.20

**Comment by jakevdp** [comment]
Thanks for the report – if you could figure out where the `convert_element_type` primitive is being called, that would help. You might start by setting `JAX_TRACEBACK_FILTERING='off'` to see the full traceback.

I tried running locally to set a breakpoint, but I'm not able to import `tjax` because of Python version incompatibilities.

**Comment by NeilGirdhar** [comment]
@jakevdp Yeah, I tried turning off the filtering, but I'm not so good at understanding the Jax internals :smile: .  I've edited the issue and removed the TJax dependency if you have time to look at it again.

**Comment by NeilGirdhar** [comment]
Okay, I think it's close to minimal now.

**Comment by NeilGirdhar** [comment]
It looks like RNG keys can no longer be primals to custom VJPs?

**Comment by jakevdp** [comment]
Thanks for the repro! Definitely an oversight. I think #18444 should fix it (I hit the `assert False` in your minimal example)

**Comment by NeilGirdhar** [comment]
I just ran my full TJax tests and they all pass now.  Thanks again for the quick fix!

**Comment by NeilGirdhar** [comment]
@jakevdp, Apparently, I didn't check my tests properly since I'm still seeing this error with the latest Jax.  Here's the stack trace:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/fixed_point/test_use_classes.py:107: in theta_bar
    return grad(f)(self).theta
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/api.py:659: in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/api.py:735: in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/api.py:2223: in _vjp
    out_primal, out_vjp = ad.vjp(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/ad.py:140: in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/ad.py:129: in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/profiler.py:334: in wrapper
    return func(*args, **kwargs)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py:774: in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/linear_util.py:191: in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
tests/fixed_point/test_use_classes.py:105: in f
    configuration = encoding.infer_state(eif).ec
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:255: in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:166: in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:2682: in bind
    return self.bind_with_trace(top_trace, args, params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:405: in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/ad.py:316: in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1551: in _pjit_jvp
    outputs = pjit_p.bind(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:2682: in bind
    return self.bind_with_trace(top_trace, args, params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:405: in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py:213: in process_primitive
    return custom_partial_eval_rules[primitive](self, *tracers, **params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1628: in _pjit_partial_eval
    all_known_outs = pjit_p.bind(*known_inputs, **known_params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:2682: in bind
    return self.bind_with_trace(top_trace, args, params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:405: in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/core.py:893: in process_primitive
    return primitive.impl(*tracers, **params)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1238: in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1222: in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1155: in _pjit_call_impl_python
    compiled = _pjit_lower(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1286: in _pjit_lower
    return _pjit_lower_cached(jaxpr, in_shardings, out_shardings, *args, **kwargs)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/pjit.py:1334: in _pjit_lower_cached
    return pxla.lower_sharding_computation(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/profiler.py:334: in wrapper
    return func(*args, **kwargs)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py:1975: in lower_sharding_computation
    nreps, tuple_args, shape_poly_state) = _cached_lowering_to_hlo(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py:1815: in _cached_lowering_to_hlo
    lowering_result = mlir.lower_jaxpr_to_module(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py:822: in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py:1260: in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py:1453: in jaxpr_subcomp
    ans = lower_per_platform(rule_ctx, str(eqn.primitive),
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py:1562: in lower_per_platform
    return kept_rules[0](ctx, *rule_args, **rule_kwargs)
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py:1904: in zeros_like_lowering
    return [full_like_aval(ctx, 0, aval)]
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py:1898: in full_like_aval
    zero = ir_constant(np.array(value, dtypes.canonicalize_dtype(aval.dtype)))
../../Library/Caches/pypoetry/virtualenvs/tjax-qBYJqOa9-py3.12/lib/python3.12/site-packages/jax/_src/dtypes.py:235: in canonicalize_dtype
    return _canonicalize_dtype(config.enable_x64.value, allow_extended_dtype, dtype)  # pytype: disable=bad-return-type
```
It's really time-consuming to produce a MWE, so please let me know if you can figure out what's going on from just this 😄

**Comment by jakevdp** [comment]
I see the stack trace, but what's the error?

**Comment by jakevdp** [comment]
Do you have a self-contained repro?

**Comment by NeilGirdhar** [comment]
@jakevdp I don't have  MWE, but you should be able to run the test if you install Python 3.10?

**Comment by jakevdp** [comment]
This traceback tells me that you're passing a custom PRNGKey in a place where it's not expected... to fix it we'll have to modify the code so that custom keys are properly handled in that place. A self-contained repro would be a good start for determining where that place is.

**Comment by NeilGirdhar** [comment]
Okay, I may eventually get to this when it blocks me, but I'm in the middle of a bigger project right now.  I was hoping the stack trace might reveal the problem 😄

**Comment by mattjj** [comment]
@NeilGirdhar fwiw I'm looking at revising some of this stuff now. Can I still repro your problem with the tjax tests [here](https://github.com/NeilGirdhar/tjax/blob/main/tests/fixed_point/test_use_classes.py) as you linked above?

**Comment by NeilGirdhar** [comment]
Just saw your message. Will test it now

**Comment by mattjj** [comment]
#19071 is one change. I haven't looked at your tests yet though so it would be blind luck if #19071 fixed anything for you. I've got this stuff paged into my head now though, so it would be a good time to take a look!

**Comment by NeilGirdhar** [comment]
Looks like it fails still.  Are you able to install tjax?
```sh
git clone tjax
cd tjax
poetry install
poetry shell
pytest tests/fixed_point/test_use_classes.py
```
Gives:
```
E       ValueError: Internal: canonicalize_dtype called on extended dtype key<fry> with allow_extended_dtype=False
E       --------------------
E       For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```
