### ISSUE TITLE
Failed to legalize rounding operation in jax-metal

### ISSUE THREAD

**Issue by ghcollin** [google/jax#18678]
### Description

The following crashes when attempting to use the GPU in jax-metal

`jax.jit(jax.numpy.round)(3.5)`

Full trace:
```
>>> jax.jit(jax.numpy.round)(1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 249, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
                                          ^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 160, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/core.py", line 2647, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 1193, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 1177, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 1113, in _pjit_call_impl_python
    always_lower=False, lowering_platform=None).compile()
                                                ^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2319, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2638, in from_hlo
    xla_executable, compile_options = _cached_compilation(
                                      ^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: <stdin>:1:0: error: failed to legalize operation 'mhlo.round_nearest_even'
<stdin>:1:0: note: called from
<stdin>:1:0: note: see current operation: %0 = "mhlo.round_nearest_even"(%arg0) : (tensor<f32>) -> tensor<f32>

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: <stdin>:1:0: error: failed to legalize operation 'mhlo.round_nearest_even'
<stdin>:1:0: note: called from
<stdin>:1:0: note: see current operation: %0 = "mhlo.round_nearest_even"(%arg0) : (tensor<f32>) -> tensor<f32>
```

On CPU, there is no error. 

### What jax/jaxlib version are you using?

jax-metal: 0.0.4, jax/jaxlib: 0.4.11 0.4.11

### Which accelerator(s) are you using?

GPU

### Additional system info?

Python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] (installed through anaconda), numpy 1.26.2, uname_result(system='Darwin', node='MacBook-Pro.local', release='23.0.0', version='Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020', machine='arm64'). 

### NVIDIA GPU info

Metal gpu info:

Chip: Apple M2 Max, memory: 32GB
OS: Sonoma, 14.0 (23A344)

**Comment by kulinseth** [comment]
@ghcollin , we have released the latest `jax-metal 0.0.5` version which fixes the issue. Can you give it a try ?

**Comment by ghcollin** [comment]
Hmm, I seem to be receiving the same error even after updating.

```
>>> import jax
>>> jax.jit(jax.numpy.round)(3.5)
Platform 'METAL' is experimental and not all JAX functionality may be correctly supported!
2023-12-22 17:31:29.057181: W pjrt_plugin/src/mps_client.cc:563] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!
Metal device set to: Apple M2 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: <stdin>:1:0: error: failed to legalize operation 'mhlo.round_nearest_even'
<stdin>:1:0: note: called from
<stdin>:1:0: note: see current operation: %0 = "mhlo.round_nearest_even"(%arg0) : (tensor<f32>) -> tensor<f32>

--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

These were the jax and jaxlib packages installed after upgrading to jax-metal 0.0.5:
```
>>> import jax, jaxlib; print(jax.__version__, jaxlib.__version__)
0.4.20 0.4.20
```

**Comment by benjaminvatterj** [comment]
Just FYI, on the new version 0.0.05 this still fails with error:
`XlaRuntimeError: UNKNOWN: <ipython-input-27-ae047f4576b7>:1:0: error: failed to legalize operation 'mhlo.round_nearest_even'`

**Comment by shuhand0** [comment]
We are looking into adding the conversion for the op.

**Comment by shuhand0** [comment]
Fixed in jax-metal 0.0.6
