### ISSUE TITLE
remat with scan

### ISSUE THREAD

**Issue by cpgoodri** [google/jax#1907]
First, let me express my excitement with the new remat functionality for automatic checkpointing! Really awesome :)

As I begin testing this out for my purposes, I am running into an issue that pops up when using lax.scan, though I'm not sure exactly where its coming from. I created a minimal example (see below), which I have tested on Colab. When both of the flags `test_remat` and `test_scan` are set to `True`, an error ultimately saying `TypeError: <class 'jax.ad_util.Zero'> is not a valid Jax type` appears. I should note that on a (much) more complicated version of this I was getting a NotImplemented error that I think is related, but I wasn't able to reproduce that in a minimal code so its possible its something else. I'd be happy to share if that would help. 

Any ideas on what is going on? Thanks in advance!

Here's the minimal example:

```
!pip install --upgrade -q https://storage.googleapis.com/jax-releases/cuda$(echo $CUDA_VERSION | sed -e 's/\.//' -e 's/\..*//')/jaxlib-$(pip search jaxlib | grep -oP '[0-9\.]+' | head -n 1)-cp36-none-linux_x86_64.whl
!pip install --upgrade -q jax

import numpy as onp
import jax.numpy as np
from jax import random, grad, lax, remat

########################################
#Error only when both of these are True#
########################################
test_remat = True
test_scan = True

key = random.PRNGKey(0)
key, split = random.split(key) 
n=5

def func(D0):
  def shift(R, dR, **unused_kwargs):
    return R + dR

  def apply_fn(R):
    return D0*R

  Rinit = random.uniform(split, (n,3), minval=0.0, maxval=5.0, dtype=np.float32)

  def move(R,i):
    F = apply_fn(R)
    return shift(R, 0.001*F), np.array([0.])
  
  if(test_remat):
    move = remat(move)
  
  if(test_scan):
    R, temp = lax.scan(move, Rinit, np.arange(2))
  else:
    R, temp = move(move(Rinit,0)[0],0)

  return R[0,0]


grad(func)(5.0)
```

**Comment by mattjj** [comment]
Thanks for the enthusiasm, and the clear repro!

This error pops up when we aren't handling the AD system's symbolic zeros correctly. Usually the fix is trivial once we spot it...

**Comment by mattjj** [comment]
#1913 should fix this. I added your code as a test case too.

We haven't had a chance to really kick the tires with `remat` yet. The design is sound but there are likely bugs (like this one). If you could eagerly raise all issues you see, like you did here, that'll be a big help to us!

**Comment by cpgoodri** [comment]
Thanks so much for fixing this so quickly, especially during the holidays! And sorry it took me so long to get back to this.

I'm still getting the NotImplemented error I mentioned above in my more complicated example. I thought these were related, but perhaps not. I just raised another issue (#1963) with a repo that is as minimal as I could make it.
