### ISSUE TITLE
Can't jit a jitted function that uses jax.lax.scan

### ISSUE THREAD

**Issue by DylanMuir** [google/jax#861]
I am getting errors when `jit`ting a function, which itself calls another `jit`ted function that uses `jax.lax.scan`. A minimal example is below:

```python
from jax import numpy as np
from jax import jit
from jax.lax import scan

def uses_scan(xs):    
    def fn(x, i):
        x = x + i
        return x, i
    
    _, os = scan(fn, 0., xs)
    return os

print('uses_scan:', uses_scan(np.ones(10)))

j = jit(uses_scan)
print('j:', j(np.ones(10)))

jj = jit(j)
print('jj:', jj(np.ones(10)))
```

Raises the error:
```
uses_scan: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
j: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-962795ca256d> in <module>
     17 
     18 jj = jit(j)
---> 19 print('jj:', jj(np.ones(10)))

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    119     _check_args(args_flat)
    120     flat_fun, out_tree = flatten_fun_leafout(f, in_tree)
--> 121     out = xla.xla_call(flat_fun, *args_flat, device_values=device_values)
    122     return out if out_tree() is leaf else tree_unflatten(out_tree(), out)
    123 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    634   if top_trace is None:
    635     with new_sublevel():
--> 636       ans = primitive.impl(f, *args, **params)
    637   else:
    638     tracers = map(top_trace.full_raise, args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_call_impl(fun, *args, **params)
    589 def xla_call_impl(fun, *args, **params):
    590   device_values = FLAGS.jax_device_values and params.pop('device_values')
--> 591   compiled_fun = xla_callable(fun, device_values, *map(abstractify, args))
    592   try:
    593     return compiled_fun(*args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in memoized_fun(f, *args)
    206       if len(cache) > max_size:
    207         cache.popitem(last=False)
--> 208       ans = call(f, *args)
    209       cache[key] = (ans, f)
    210     return ans

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_callable(fun, device_values, *abstract_args)
    602   pvals = [pe.PartialVal((aval, core.unit)) for aval in abstract_args]
    603   with core.new_master(pe.JaxprTrace, True) as master:
--> 604     jaxpr, (pval, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
    605     assert not env  # no subtraces here (though cond might eventually need them)
    606     compiled, result_shape = compile_jaxpr(jaxpr, consts, *abstract_args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    145 
    146     del gen
--> 147     ans = self.f(*args, **dict(self.params, **kwargs))
    148     del args
    149     while stack:

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    119     _check_args(args_flat)
    120     flat_fun, out_tree = flatten_fun_leafout(f, in_tree)
--> 121     out = xla.xla_call(flat_fun, *args_flat, device_values=device_values)
    122     return out if out_tree() is leaf else tree_unflatten(out_tree(), out)
    123 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    637   else:
    638     tracers = map(top_trace.full_raise, args)
--> 639     ans = full_lower(top_trace.process_call(primitive, f, tracers, params))
    640   return apply_todos(env_trace_todo(), ans)
    641 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in process_call(self, call_primitive, f, tracers, params)
    109     in_pvs, in_consts = unzip2([t.pval for t in tracers])
    110     fun, aux = partial_eval(f, self, in_pvs)
--> 111     out_pv_const, consts = call_primitive.bind(fun, *in_consts, **params)
    112     out_pv, jaxpr, env = aux()
    113     const_tracers = map(self.new_instantiated_const, consts)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    634   if top_trace is None:
    635     with new_sublevel():
--> 636       ans = primitive.impl(f, *args, **params)
    637   else:
    638     tracers = map(top_trace.full_raise, args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_call_impl(fun, *args, **params)
    589 def xla_call_impl(fun, *args, **params):
    590   device_values = FLAGS.jax_device_values and params.pop('device_values')
--> 591   compiled_fun = xla_callable(fun, device_values, *map(abstractify, args))
    592   try:
    593     return compiled_fun(*args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in memoized_fun(f, *args)
    206       if len(cache) > max_size:
    207         cache.popitem(last=False)
--> 208       ans = call(f, *args)
    209       cache[key] = (ans, f)
    210     return ans

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_callable(fun, device_values, *abstract_args)
    602   pvals = [pe.PartialVal((aval, core.unit)) for aval in abstract_args]
    603   with core.new_master(pe.JaxprTrace, True) as master:
--> 604     jaxpr, (pval, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
    605     assert not env  # no subtraces here (though cond might eventually need them)
    606     compiled, result_shape = compile_jaxpr(jaxpr, consts, *abstract_args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    145 
    146     del gen
--> 147     ans = self.f(*args, **dict(self.params, **kwargs))
    148     del args
    149     while stack:

<ipython-input-26-962795ca256d> in uses_scan(xs)
      8         return x, i
      9 
---> 10     _, os = scan(fn, 0., xs)
     11     return os
     12 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in scan(f, init, xs)
    588   length = _leading_dim_size(xs)
    589   out = scan_p.bind(core.pack(consts), init, xs,
--> 590                     forward=True, length=length, jaxpr=jaxpr)
    591   return build_tree(out_tree(), out)
    592 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in scan_bind(consts, init, xs, forward, length, jaxpr)
    898     assert init_aval == carry_aval
    899   return core.Primitive.bind(scan_p, consts, init, xs,
--> 900                              forward=forward, length=length, jaxpr=jaxpr)
    901 
    902 scan_p = core.Primitive("scan")

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in bind(self, *args, **kwargs)
    118 
    119     tracers = map(top_trace.full_raise, args)
--> 120     out_tracer = top_trace.process_primitive(self, tracers, kwargs)
    121     return full_lower(out_tracer)
    122 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in process_primitive(self, primitive, tracers, params)
     91     if primitive in custom_partial_eval_rules:
     92       partial_eval = custom_partial_eval_rules[primitive]
---> 93       return partial_eval(self, *tracers, **params)
     94     else:
     95       tracers = map(self.instantiate_const, tracers)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in _scan_partial_eval(trace, *tracers, **kwargs)
    704 
    705   out_carry, (ys, residuals) = scan_p.bind(
--> 706       *in_consts, forward=forward, length=length, jaxpr=jaxpr_1)
    707   out_const = core.pack((out_carry, ys))
    708   residuals_tracer = trace.new_instantiated_const(core.pack(residuals))

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in scan_bind(consts, init, xs, forward, length, jaxpr)
    898     assert init_aval == carry_aval
    899   return core.Primitive.bind(scan_p, consts, init, xs,
--> 900                              forward=forward, length=length, jaxpr=jaxpr)
    901 
    902 scan_p = core.Primitive("scan")

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in bind(self, *args, **kwargs)
    118 
    119     tracers = map(top_trace.full_raise, args)
--> 120     out_tracer = top_trace.process_primitive(self, tracers, kwargs)
    121     return full_lower(out_tracer)
    122 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in process_primitive(self, primitive, tracers, params)
     91     if primitive in custom_partial_eval_rules:
     92       partial_eval = custom_partial_eval_rules[primitive]
---> 93       return partial_eval(self, *tracers, **params)
     94     else:
     95       tracers = map(self.instantiate_const, tracers)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in _scan_partial_eval(trace, *tracers, **kwargs)
    684     second_components = (sc_consts, sc_carry, sc_xs)
    685     jaxpr_1, jaxpr_2, sc_out = pe.partial_eval_jaxpr(jaxpr, second_components,
--> 686                                                      instantiate=(sc_carry, False))
    687     sc_carry_out, sc_ys = sc_out
    688     if _binary_lattice_eq(sc_carry_out, sc_carry):

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in partial_eval_jaxpr(jaxpr, second_components, instantiate)
    604   pvals = map(as_pval2, jaxpr.in_avals, second_components)
    605   jaxpr_1, out_pval, consts_1 = trace_to_jaxpr(
--> 606       lu.wrap_init(fun), pvals, instantiate=True)
    607   out_pv_c, out_pv_b, jaxpr_2 = cell[0]
    608 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, **kwargs)
    389   with new_master(JaxprTrace) as master:
    390     fun = trace_to_subjaxpr(fun, master, instantiate)
--> 391     jaxpr, (out_pval, consts, env) = fun.call_wrapped(pvals)
    392     assert not env
    393     del master

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    145 
    146     del gen
--> 147     ans = self.f(*args, **dict(self.params, **kwargs))
    148     del args
    149     while stack:

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in fun(*vals)
    593   def fun(*vals):
    594     pvals = map(as_pval, jaxpr.in_avals, second_components, vals)
--> 595     jaxpr_2, out_pval, consts_2 = trace_to_jaxpr(f, pvals, instantiate=instantiate)
    596     (out_pv_c, out_pv_b), out_const = out_pval
    597     if out_const is core.unit:

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, **kwargs)
    389   with new_master(JaxprTrace) as master:
    390     fun = trace_to_subjaxpr(fun, master, instantiate)
--> 391     jaxpr, (out_pval, consts, env) = fun.call_wrapped(pvals)
    392     assert not env
    393     del master

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(***failed resolving arguments***)
    149     while stack:
    150       gen, out_store = stack.pop()
--> 151       ans = gen.send(ans)
    152       if out_store is not None:
    153         ans, side = ans

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in trace_to_subjaxpr(master, instantiate, pvals)
    405   out_tracer = instantiate_const_at(trace, instantiate, out_tracer)
    406 
--> 407   jaxpr, consts, env = tracers_to_jaxpr(in_tracers, out_tracer)
    408   out_pval = out_tracer.pval
    409   del trace, in_tracers, out_tracer

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in tracers_to_jaxpr(in_tracers, out_tracer)
    444   t_to_var = defaultdict(newvar)
    445   var = lambda t: t_to_var[id(t)]
--> 446   sorted_tracers = toposort(out_tracer)
    447   invars = map(var, in_tracers)
    448   eqns = []

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/util.py in toposort(end_node)
    107     else:
    108       child_counts[id(node)] = 1
--> 109       stack.extend(node.parents)
    110 
    111   sorted_nodes = []

AttributeError: 'JaxTuple' object has no attribute 'parents'
```

This is a silly example, but I would hope that `jit`ting should work regardless of whether a function I call is `jit`ted or not. For example, an object might internally use a `jit`ted evaluation function for performance reasons. I want to use this evaluation function inside my own loss function, and then use `jit(grad(loss))` in an optimiser.

**Comment by DylanMuir** [comment]
I am using jax 0.1.35 on python 3.6.7.

**Comment by mattjj** [comment]
Can you update jax (at time of writing, to 0.1.37) and try again? This sounds like a bug we've already fixed. (In fact, I verified that your test works on the master branch.)

>  I would hope that jitting should work regardless of whether a function I call is jitted or not

Indeed, that's the aim!

**Comment by DylanMuir** [comment]
Thanks @mattjj, I'll try and report back.

**Comment by DylanMuir** [comment]
Updating to 0.1.37 didn't resolve the error. Updating `jaxlib` to 0.1.20 also didn't resolve the error.
```
jax ver: 0.1.37
jaxlib ver: 0.1.20
uses_scan: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
j: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d54b675a3c43> in <module>
     22 
     23 jj = jit(j)
---> 24 print('jj:', jj(np.ones(10)))

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    121     _check_args(args_flat)
    122     flat_fun, out_tree = flatten_fun_leafout(f, in_tree)
--> 123     out = xla.xla_call(flat_fun, *args_flat, device_values=device_values)
    124     return out if out_tree() is leaf else tree_unflatten(out_tree(), out)
    125 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    653   if top_trace is None:
    654     with new_sublevel():
--> 655       ans = primitive.impl(f, *args, **params)
    656   else:
    657     tracers = map(top_trace.full_raise, args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_call_impl(fun, *args, **params)
    651 def xla_call_impl(fun, *args, **params):
    652   device_values = FLAGS.jax_device_values and params.pop('device_values')
--> 653   compiled_fun = xla_callable(fun, device_values, *map(abstractify, args))
    654   try:
    655     return compiled_fun(*args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in memoized_fun(f, *args)
    206       if len(cache) > max_size:
    207         cache.popitem(last=False)
--> 208       ans = call(f, *args)
    209       cache[key] = (ans, f)
    210     return ans

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_callable(fun, device_values, *abstract_args)
    664   pvals = [pe.PartialVal((aval, core.unit)) for aval in abstract_args]
    665   with core.new_master(pe.JaxprTrace, True) as master:
--> 666     jaxpr, (pval, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
    667     assert not env  # no subtraces here (though cond might eventually need them)
    668     compiled, result_shape = compile_jaxpr(jaxpr, consts, *abstract_args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    145 
    146     del gen
--> 147     ans = self.f(*args, **dict(self.params, **kwargs))
    148     del args
    149     while stack:

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    121     _check_args(args_flat)
    122     flat_fun, out_tree = flatten_fun_leafout(f, in_tree)
--> 123     out = xla.xla_call(flat_fun, *args_flat, device_values=device_values)
    124     return out if out_tree() is leaf else tree_unflatten(out_tree(), out)
    125 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    656   else:
    657     tracers = map(top_trace.full_raise, args)
--> 658     ans = full_lower(top_trace.process_call(primitive, f, tracers, params))
    659   return apply_todos(env_trace_todo(), ans)
    660 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in process_call(self, call_primitive, f, tracers, params)
    111     in_pvs, in_consts = unzip2([t.pval for t in tracers])
    112     fun, aux = partial_eval(f, self, in_pvs)
--> 113     out_pv_const, consts = call_primitive.bind(fun, *in_consts, **params)
    114     out_pv, jaxpr, env = aux()
    115     const_tracers = map(self.new_instantiated_const, consts)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    653   if top_trace is None:
    654     with new_sublevel():
--> 655       ans = primitive.impl(f, *args, **params)
    656   else:
    657     tracers = map(top_trace.full_raise, args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_call_impl(fun, *args, **params)
    651 def xla_call_impl(fun, *args, **params):
    652   device_values = FLAGS.jax_device_values and params.pop('device_values')
--> 653   compiled_fun = xla_callable(fun, device_values, *map(abstractify, args))
    654   try:
    655     return compiled_fun(*args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in memoized_fun(f, *args)
    206       if len(cache) > max_size:
    207         cache.popitem(last=False)
--> 208       ans = call(f, *args)
    209       cache[key] = (ans, f)
    210     return ans

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_callable(fun, device_values, *abstract_args)
    664   pvals = [pe.PartialVal((aval, core.unit)) for aval in abstract_args]
    665   with core.new_master(pe.JaxprTrace, True) as master:
--> 666     jaxpr, (pval, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
    667     assert not env  # no subtraces here (though cond might eventually need them)
    668     compiled, result_shape = compile_jaxpr(jaxpr, consts, *abstract_args)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    145 
    146     del gen
--> 147     ans = self.f(*args, **dict(self.params, **kwargs))
    148     del args
    149     while stack:

<ipython-input-2-d54b675a3c43> in uses_scan(xs)
     13         return x, i
     14 
---> 15     _, os = scan(fn, 0., xs)
     16     return os
     17 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in scan(f, init, xs)
    548   length = _leading_dim_size(xs)
    549   out = scan_p.bind(core.pack(consts), init, xs,
--> 550                     forward=True, length=length, jaxpr=jaxpr)
    551   return build_tree(out_tree(), out)
    552 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in scan_bind(consts, init, xs, forward, length, jaxpr)
    858     # assert init_aval == carry_aval  # TODO(mattjj): handle unit tree prefixes
    859   return core.Primitive.bind(scan_p, consts, init, xs,
--> 860                              forward=forward, length=length, jaxpr=jaxpr)
    861 
    862 scan_p = core.Primitive("scan")

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in bind(self, *args, **kwargs)
    137 
    138     tracers = map(top_trace.full_raise, args)
--> 139     out_tracer = top_trace.process_primitive(self, tracers, kwargs)
    140     return full_lower(out_tracer)
    141 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in process_primitive(self, primitive, tracers, params)
     93     if primitive in custom_partial_eval_rules:
     94       partial_eval = custom_partial_eval_rules[primitive]
---> 95       return partial_eval(self, *tracers, **params)
     96     else:
     97       tracers = map(self.instantiate_const, tracers)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in _scan_partial_eval(trace, *tracers, **kwargs)
    664 
    665   out_carry, (ys, residuals) = scan_p.bind(
--> 666       *in_consts, forward=forward, length=length, jaxpr=jaxpr_1)
    667   out_const = core.pack((out_carry, ys))
    668   residuals_tracer = trace.new_instantiated_const(core.pack(residuals))

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in scan_bind(consts, init, xs, forward, length, jaxpr)
    858     # assert init_aval == carry_aval  # TODO(mattjj): handle unit tree prefixes
    859   return core.Primitive.bind(scan_p, consts, init, xs,
--> 860                              forward=forward, length=length, jaxpr=jaxpr)
    861 
    862 scan_p = core.Primitive("scan")

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/core.py in bind(self, *args, **kwargs)
    137 
    138     tracers = map(top_trace.full_raise, args)
--> 139     out_tracer = top_trace.process_primitive(self, tracers, kwargs)
    140     return full_lower(out_tracer)
    141 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in process_primitive(self, primitive, tracers, params)
     93     if primitive in custom_partial_eval_rules:
     94       partial_eval = custom_partial_eval_rules[primitive]
---> 95       return partial_eval(self, *tracers, **params)
     96     else:
     97       tracers = map(self.instantiate_const, tracers)

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/lax/lax_control_flow.py in _scan_partial_eval(trace, *tracers, **kwargs)
    644     second_components = (sc_consts, sc_carry, sc_xs)
    645     jaxpr_1, jaxpr_2, sc_out = pe.partial_eval_jaxpr(jaxpr, second_components,
--> 646                                                      instantiate=(sc_carry, False))
    647     sc_carry_out, sc_ys = sc_out
    648     if _binary_lattice_eq(sc_carry_out, sc_carry):

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in partial_eval_jaxpr(jaxpr, second_components, instantiate)
    593   pvals = map(as_pval2, jaxpr.in_avals, second_components)
    594   jaxpr_1, out_pval, consts_1 = trace_to_jaxpr(
--> 595       lu.wrap_init(fun), pvals, instantiate=True)
    596   out_pv_c, out_pv_b, jaxpr_2 = cell[0]
    597 

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, **kwargs)
    393   with new_master(JaxprTrace) as master:
    394     fun = trace_to_subjaxpr(fun, master, instantiate)
--> 395     jaxpr, (out_pval, consts, env) = fun.call_wrapped(pvals)
    396     assert not env
    397     del master

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    145 
    146     del gen
--> 147     ans = self.f(*args, **dict(self.params, **kwargs))
    148     del args
    149     while stack:

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in fun(*vals)
    582   def fun(*vals):
    583     pvals = map(as_pval, jaxpr.in_avals, second_components, vals)
--> 584     jaxpr_2, out_pval, consts_2 = trace_to_jaxpr(f, pvals, instantiate=instantiate)
    585     (out_pv_c, out_pv_b), out_const = out_pval
    586     if out_const is core.unit:

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, **kwargs)
    393   with new_master(JaxprTrace) as master:
    394     fun = trace_to_subjaxpr(fun, master, instantiate)
--> 395     jaxpr, (out_pval, consts, env) = fun.call_wrapped(pvals)
    396     assert not env
    397     del master

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/linear_util.py in call_wrapped(***failed resolving arguments***)
    149     while stack:
    150       gen, out_store = stack.pop()
--> 151       ans = gen.send(ans)
    152       if out_store is not None:
    153         ans, side = ans

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in trace_to_subjaxpr(master, instantiate, pvals)
    409   out_tracer = instantiate_const_at(trace, instantiate, out_tracer)
    410 
--> 411   jaxpr, consts, env = tracers_to_jaxpr(in_tracers, out_tracer)
    412   out_pval = out_tracer.pval
    413   del trace, in_tracers, out_tracer

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in tracers_to_jaxpr(in_tracers, out_tracer)
    448   t_to_var = defaultdict(newvar)
    449   var = lambda t: t_to_var[id(t)]
--> 450   sorted_tracers = toposort(out_tracer)
    451   invars = map(var, in_tracers)
    452   eqns = []

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/util.py in toposort(end_node)
    107     else:
    108       child_counts[id(node)] = 1
--> 109       stack.extend(node.parents)
    110 
    111   sorted_nodes = []

AttributeError: 'JaxTuple' object has no attribute 'parents'
```

**Comment by mattjj** [comment]
Okay, since I wasn't able to repro on master, the solution must be to make a new pypi release!

**Comment by DylanMuir** [comment]
🤣

**Comment by DylanMuir** [comment]
Let me know when you're ready for me to upgrade and check again.

**Comment by mattjj** [comment]
Just uploaded jax 0.1.38. I expect the error will go away, but let us know!

**Comment by DylanMuir** [comment]
I confirm that it works now with jax 0.1.38. Thanks for chasing this down!

```
jax ver: 0.1.38
jaxlib ver: 0.1.20
uses_scan: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
j: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
jj: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```

**Comment by hawkinsp** [comment]
Great! Thanks for the bug report!

**Comment by mattjj** [comment]
FYI a user found another instance of this kind of error that we squashed in #890 (but haven't pushed to pypi yet at the time of writing).

**Comment by DylanMuir** [comment]
You guys are on fire :) Thanks for the heads-up.
